In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
# 2. 加载鸢尾花数据集
iris = datasets.load_iris()

X = iris.data  # 特征矩阵
y = iris.target  # 目标变量

In [5]:
#特征标准化
scaler   = StandardScaler()#标准化目的是将数据缩放到一个均值为 0，标准差为 1 的正太分布，消除不同特征量纲的影响，尤其是像支持向量机 (SVM)、逻辑回归、神经网络等基于梯度的模型。
X_scaled = scaler.fit_transform(X)

In [7]:
# 划分训练集和测试集（80% 训练集，20% 测试集）
X_train, X_test, y_train, y_test = train_test_split(X_scaled, 
                                                    y, 
                                                    test_size=0.2, 
                                                    random_state=42)

In [9]:
#逻辑回归模型
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)  # max_iter 是迭代次数，默认为100，这里设为200以保证收敛
model.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [11]:
y_pred = model.predict(X_test)

In [13]:
accuracy = accuracy_score(y_test, y_pred)
print(f"模型的准确率: {accuracy:.2f}")

# 打印分类报告
print("分类报告:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# 打印混淆矩阵
print("混淆矩阵:")
print(confusion_matrix(y_test, y_pred))

模型的准确率: 1.00
分类报告:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

混淆矩阵:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
